import { v4 as uuid } from 'uuid';

export type AutoGeneratedProps = {
    id: string;
    archived: boolean;
    archivedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
};

export const getAutoGeneratedProps = (): AutoGeneratedProps => {
    return {
        id: uuid(),
        archived: false,
        archivedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
    };
};
