packages:
    - apps/*
    - packages/**
catalog:
    '@babel/core': ^7.24.5
    '@expo-google-fonts/nunito': ^0.2.3
    '@expo-google-fonts/poppins': ^0.2.3
    '@expo/metro-runtime': ^3.2.1
    '@faker-js/faker': ^9.2.0
    '@gorhom/bottom-sheet': ^5
    '@hookform/resolvers': ^3.9.0
    '@ianvs/prettier-plugin-sort-imports': ^4.3.1
    '@prisma/client': ^5.21.1
    '@react-native-async-storage/async-storage': ^1.23.1
    '@react-native-community/datetimepicker': ^8.2.0
    '@react-native-community/netinfo': ^11.3.1
    '@react-native-community/slider': ^4.5.2
    '@storybook/addon-actions': ^8.4.2
    '@storybook/addon-controls': ^8.4.2
    '@storybook/addon-essentials': ^8.4.2
    '@storybook/addon-links': ^8.4.2
    '@storybook/addon-ondevice-actions': ^8.4.2
    '@storybook/addon-ondevice-backgrounds': ^8.4.2
    '@storybook/addon-ondevice-controls': ^8.4.2
    '@storybook/addon-ondevice-notes': ^8.4.2
    '@storybook/core': ^8.4.2
    '@storybook/react': ^8.4.2
    '@storybook/react-native': ^8.4.2
    '@storybook/test': ^8.4.2
    '@supabase/supabase-js': ^2.45.6
    '@tanstack/react-query': ^5.59.16
    '@trpc/client': ^11.0.0-rc.593
    '@trpc/react-query': ^11.0.0-rc.593
    '@trpc/server': ^11.0.0-rc.593
    '@tsconfig/recommended': ^1.0.6
    '@types/chroma-js': ^2.4.4
    '@types/express': ^5.0.0
    '@types/identicon.js': ^2.3.5
    '@types/jsonwebtoken': ^9.0.7
    '@types/lodash': ^4.17.10
    '@types/md5': ^2.3.5
    '@types/moment': ^2.13.0
    '@types/react': ^18.2.79
    '@types/react-dom': ^18.2.25
    '@types/validator': ^13.12.2
    '@typescript-eslint/eslint-plugin': ^5.62.0
    '@typescript-eslint/parser': ^5.62.0
    babel-loader: ^8.4.1
    babel-preset-expo: ^11.0.11
    blurhash: ^2.0.5
    chroma-js: ^3.1.1
    dayjs: ^1.11.13
    eslint: ^8.57.0
    eslint-config-universe: ^12.1.0
    eslint-plugin-react-hooks: ^5.0.0
    expo: ^51.0.39
    expo-constants: ^16.0.2
    expo-dev-client: ^4.0.29
    expo-font: ^12.0.10
    expo-image: ^1.13.0
    expo-image-picker: ^15.0.7
    expo-linear-gradient: ^13.0.2
    expo-linking: ^6.3.1
    expo-router: ^3.5.24
    expo-status-bar: ^1.12.1
    expo-updates: ^0.25.27
    express: ^4.21.0
    identicon.js: ^2.3.3
    jotai: ^2.10.1
    jsonwebtoken: ^9.0.2
    lodash: ^4.17.21
    lucide-react-native: ^0.453.0
    md5: ^2.3.0
    moment: ^2.30.1
    prettier: ^3.3.3
    prisma: ^5.21.1
    react: ^18.2.0
    react-dom: ^18.2.0
    react-hook-form: ^7.53.1
    react-native: ^0.74.5
    react-native-country-flag: ^2.0.2
    react-native-gesture-handler: ^2.16.1
    react-native-get-random-values: ^1.11.0
    react-native-keyboard-controller: ^1.14.1
    react-native-reanimated: ^3.10.1
    react-native-safe-area-context: ^4.10.5
    react-native-screens: ^3.31.1
    react-native-svg: ^15.2.0
    react-native-url-polyfill: ^2.0.0
    react-native-uuid: ^2.0.3
    react-native-web: ^0.19.11
    sharp: ^0.33.5
    superjson: ^2.2.1
    tsup: ^8.3.0
    tsx: ^4.19.2
    turbo: ^2.1.3
    typescript: ^5.6.3
    uuid: ^11.0.3
    validator: ^13.12.0
    zx: ^8.2.2
