packages:
    - apps/*
    - packages/**
    - "!**/build/**"
catalog:
    "@anatine/zod-mock": ^3.13.4
    "@babel/core": ^7.24.5
    "@expo-google-fonts/nunito": ^0.2.3
    "@expo-google-fonts/poppins": ^0.2.3
    "@expo-google-fonts/ubuntu": ^0.2.3
    "@expo/metro-runtime": ^4.0.1
    "@faker-js/faker": ^9.2.0
    "@gorhom/bottom-sheet": ^5
    "@hookform/error-message": ^2.0.1
    "@hookform/resolvers": ^3.9.0
    "@ianvs/prettier-plugin-sort-imports": ^4.3.1
    "@prisma/client": ^5.21.1
    "@react-native-async-storage/async-storage": ^1.23.1
    "@react-native-community/datetimepicker": ^8.2.0
    "@react-native-community/netinfo": ^11.4.1
    "@react-native-community/slider": ^4.5.5
    "@storybook/addon-actions": ^8.4.2
    "@storybook/addon-controls": ^8.4.2
    "@storybook/addon-essentials": ^8.4.2
    "@storybook/addon-links": ^8.4.2
    "@storybook/addon-ondevice-actions": ^8.4.2
    "@storybook/addon-ondevice-backgrounds": ^8.4.2
    "@storybook/addon-ondevice-controls": ^8.4.2
    "@storybook/addon-ondevice-notes": ^8.4.2
    "@storybook/core": ^8.4.2
    "@storybook/react": ^8.4.2
    "@storybook/react-native": ^8.4.2
    "@storybook/test": ^8.4.2
    "@supabase/supabase-js": ^2.47.16
    "@tanstack/react-query": ^5.59.16
    "@trpc/client": ^11.0.0-rc.593
    "@trpc/react-query": ^11.0.0-rc.593
    "@trpc/server": ^11.0.0-rc.593
    "@tsconfig/recommended": ^1.0.6
    "@types/chroma-js": ^2.4.4
    "@types/express": ^5.0.0
    "@types/jsonwebtoken": ^9.0.7
    "@types/lodash": ^4.17.10
    "@types/react": ^18.3.20
    "@types/react-dom": ^18.3.6
    "@types/shortid": ^2.2.0
    "@types/validator": ^13.12.2
    "@typescript-eslint/eslint-plugin": ^5.62.0
    "@typescript-eslint/parser": ^5.62.0
    "@zenstackhq/runtime": ^2.11.2
    babel-loader: ^8.4.1
    babel-preset-expo: ^12.0.11
    blurhash: ^2.0.5
    chroma-js: ^3.1.1
    dayjs: ^1.11.13
    dotenv: ^16.4.7
    env-cmd: ^10.1.0
    eslint: ^8.57.0
    eslint-config-universe: ^12.1.0
    eslint-plugin-react-hooks: ^5.0.0
    expo: ^52.0.44
    expo-blur: ~14.0.3
    expo-clipboard: ~7.0.1
    expo-constants: ^17.0.8
    expo-dev-client: ^5.0.20
    expo-font: ^13.0.4
    expo-image: ^2.0.7
    expo-image-picker: ^16.0.6
    expo-linear-gradient: ^14.0.2
    expo-linking: ^7.0.5
    expo-router: ^4.0.20
    expo-splash-screen: ~0.29.22
    expo-status-bar: ^2.0.1
    expo-updates: ^0.27.4
    express: ^4.21.0
    jotai: ^2.10.1
    jsonwebtoken: ^9.0.2
    lodash: ^4.17.21
    lucide-react-native: ^0.453.0
    moti: ^0.29.0
    prettier: ^3.3.3
    prisma: ^5.21.1
    react: ^18.3.1
    react-dom: ^18.3.1
    react-hook-form: ^7.53.1
    react-native: ^0.76.9
    react-native-collapsible-tab-view: ^8.0.0
    react-native-country-flag: ^2.0.2
    react-native-gesture-handler: ^2.20.2
    react-native-get-random-values: ^1.11.0
    react-native-keyboard-controller: ^1.16.0
    react-native-pager-view: ^6.5.1
    react-native-reanimated: ^3.16.7
    react-native-safe-area-context: ^4.12.0
    react-native-screens: ^4.4.0
    react-native-svg: ^15.8.0
    react-native-url-polyfill: ^2.0.0
    react-native-uuid: ^2.0.3
    react-native-web: ^0.19.13
    sharp: ^0.33.5
    shortid: ^2.2.17
    superjson: ^2.2.1
    tsup: ^8.3.0
    tsx: ^4.19.2
    turbo: ^2.1.3
    typescript: ^5.6.3
    uuid: ^11.0.3
    validator: ^13.12.0
    vitest: ^2.1.8
    zenstack: ^2.11.2
    zod: ^3.24.1
    zx: ^8.2.2
