name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
    node-version:
        description: Version of Node to use
        default: 20.x

    eas-version:
        description: Version of EAS CLI to use
        default: latest

    expo-token:
        description: Expo token to authenticate with
        required: false

runs:
    using: composite
    steps:
        - name: 🏗 Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              version: ${{ inputs.pnpm-version }}

        - name: 🏗 Setup Node
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              # 🚨 Remove the cache option to disable caching
              # cache: pnpm

        - name: 🏗 Setup Expo
          uses: expo/expo-github-action@v8
          with:
              eas-version: ${{ inputs.eas-version }}
              token: ${{ inputs.expo-token }}

        - name: 🚨 Ensure a fresh install (Remove Cache)
          run: |
              rm -rf node_modules pnpm-lock.yaml
              rm -rf ~/.cache/pnpm
              rm -rf apps/*/.turbo packages/*/.turbo
              rm -rf .turbo
          shell: bash

        - name: 📦 Install dependencies
          run: pnpm install --prefer-offline
          shell: bash

        # 🚨 Remove the Turbo Cache Step
        # - name: ♻️ Restore cache
        #   uses: actions/cache@v4
        #   with:
        #       key: turbo-${{ runner.os }}-${{ github.sha }}
        #       restore-keys: |
        #           turbo-${{ runner.os }}
        #       path: |
        #           node_modules/.cache/turbo
        #           apps/*/.turbo
        #           packages/*/.turbo
